version: '3.8'

services:
  # CONTENEDOR 1: Base de Datos InfluxDB
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_iot
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=mi_empresa
      - DOCKER_INFLUXDB_INIT_BUCKET=sensores
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mi-token-super-secreto-12345
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - iot_network

  # CONTENEDOR 2: Simulador de Sensor
  sensor:
    build: ./sensor
    container_name: sensor_simulator
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=mi-token-super-secreto-12345
      - INFLUXDB_ORG=mi_empresa
      - INFLUXDB_BUCKET=sensores
    networks:
      - iot_network
    restart: unless-stopped

  # CONTENEDOR 3: Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_iot
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - influxdb
    networks:
      - iot_network


# VOLÃšMENES (para persistir datos)

volumes:
  influxdb_data:
  grafana_data:

# RED (para que se comuniquen)

networks:
  iot_network:
    driver: bridge