apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: influxdb-iot  # ‚Üê UID FIJO - siempre el mismo
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mi_empresa
      defaultBucket: sensores
      tlsSkipVerify: true
    secureJsonData:
      token: mi-token-super-secreto-12345
    isDefault: true
    editable: false